using UsefulParser.Generated;

namespace UsefulParser;

public class Program {
  public static void Main(string[] args) {
    Console.WriteLine("Welcome to UsefulParser, generated by Giraffe");
    Console.WriteLine("I can't tell you what language it parses, but it's a very practical one!");

    while (true) {
      Console.Write("> ");

      string? line = Console.ReadLine();

      if (line is null) { // User input ^D
        break;
      }

      Scanner scanner = new(line);
      Parser parser = new(scanner);

      try {
        parser.Parse();
        Console.WriteLine("Accepted");
      }
      catch (Exception e) {
        Console.WriteLine($"Not accepted ({e.Message})");
      }
    }
  }
}