using ExampleRecognizer.Generated;

namespace ExampleRecognizer;

public class Program {
  public static void Main(string[] args) {
    Console.WriteLine("Welcome to ExampleRecognizer, generated by Giraffe");
    Console.WriteLine("Accepts strings like /a?b?cd?e?/, ^D to exit");

    while (true) {
      Console.Write("> ");

      string? line = Console.ReadLine();

      if (line is null) { // User input ^D
        break;
      }

      Scanner scanner = new(line);
      Parser parser = new(scanner);

      try {
        parser.Parse();
        Console.WriteLine("Accepted");
      }
      catch (Exception e) {
        Console.WriteLine($"Not accepted ({e.Message})");
      }
    }
  }
}