using ExprParser.Generated;

namespace ExprParser;

public class Program {
  public static void Main(string[] args) {
    Console.WriteLine("Welcome to ExprParser, generated by Giraffe");
    Console.WriteLine("Parses expressions like \"5+2\", \"25*4-1\", \"5+7+3/2\", ^D to exit");

    while (true) {
      Console.Write("> ");

      string? line = Console.ReadLine();

      if (line is null) { // User input ^D
        break;
      }

      Scanner scanner = new(line);
      Parser parser = new(scanner);

      try {
        ParseTree tree = parser.Parse();
        ExprVisitor visitor = new();
        Console.WriteLine(visitor.Visit(tree));
      }
      catch (Exception e) {
        Console.WriteLine($"Error: {e.Message}");
      }
    }
  }
}